scene_objects:
- {type: "box", frame: "world", position: [0.5,0.5,0.5], quaternion: [0, 0, 0, 1]}
#- {type: "big_box", frame: "world", position: [0.5,0.5,0.5], quaternion: [1, 0, 0, 1]}
#- {type: "big_box", frame: "world", position: [0.5,0.5,0.5], quaternion: [0, 1, 0, 1]}
