object_geometries:
  scatola    : {box: [0.1, 0.1, 0.1], color: [1,0.0,0.0,1]}
  box    : {box: [0.15, 0.15, 0.45], color: [0.75,0.75,0.75,1]}
  big_box_cartesian : {box: [0.4, 0.4, 0.6], color: [0.5,0.5,0.5,1]}
